# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/burnbox.rb.tmpl in
# github.com/kfet/burnbox.
class Burnbox < Formula
  desc "Server-blind, one-time secret sharing (burn-after-reading)"
  homepage "https://github.com/kfet/burnbox"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/burnbox/releases/download/v0.1.2/burnbox-0.1.2-darwin-arm64.tar.gz"
      sha256 "a76109fcfba8589801e1c48b487beb52d094462084c1ae9520df68db296e9295"
    end
    on_intel do
      url "https://github.com/kfet/burnbox/releases/download/v0.1.2/burnbox-0.1.2-darwin-amd64.tar.gz"
      sha256 "1a218762aaf6dd8a0dc7d2da032acdd06cc13010eba23ae9c7ff2a7220b9d2c6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/burnbox/releases/download/v0.1.2/burnbox-0.1.2-linux-arm64.tar.gz"
      sha256 "14a9d111ad01c7a34dcf64f2b6209357b23d4f23adaf7cfd146b5452d54480e6"
    end
    on_intel do
      url "https://github.com/kfet/burnbox/releases/download/v0.1.2/burnbox-0.1.2-linux-amd64.tar.gz"
      sha256 "30161b837033b5be14fbe9d441e1a309c4b5fbf3b53d3aceb08050344e795ac5"
    end
  end

  def install
    bin.install "burnbox"
  end

  test do
    assert_match "burnbox", shell_output("#{bin}/burnbox version 2>&1")
  end
end
