# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/burnbox.rb.tmpl in
# github.com/kfet/burnbox.
class Burnbox < Formula
  desc "Server-blind, one-time secret sharing (burn-after-reading)"
  homepage "https://github.com/kfet/burnbox"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/burnbox/releases/download/v0.1.6/burnbox-0.1.6-darwin-arm64.tar.gz"
      sha256 "28d4524036735896b47ad46e309e04dab3ea924ae32f3f7494ab5f54401de0cd"
    end
    on_intel do
      url "https://github.com/kfet/burnbox/releases/download/v0.1.6/burnbox-0.1.6-darwin-amd64.tar.gz"
      sha256 "605c75c1247a77878b7bb975332f0fe225e8e35731d71b7424b6e9b83a69788a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/burnbox/releases/download/v0.1.6/burnbox-0.1.6-linux-arm64.tar.gz"
      sha256 "00f348d60cb6940d35acc80831a893f4338a69a7b679f8dbf48e1618dc3c82c0"
    end
    on_intel do
      url "https://github.com/kfet/burnbox/releases/download/v0.1.6/burnbox-0.1.6-linux-amd64.tar.gz"
      sha256 "cf44f67ccdbac509963c130108d39e47d53ae90e14ddb547041b4cc8198bf48b"
    end
  end

  def install
    bin.install "burnbox"
  end

  test do
    assert_match "burnbox", shell_output("#{bin}/burnbox version 2>&1")
  end
end
