# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/burnbox.rb.tmpl in
# github.com/kfet/burnbox.
class Burnbox < Formula
  desc "Server-blind, one-time secret sharing (burn-after-reading)"
  homepage "https://github.com/kfet/burnbox"
  version "0.1.7"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/burnbox/releases/download/v0.1.7/burnbox-0.1.7-darwin-arm64.tar.gz"
      sha256 "9afebab646dbdfb34c1dca3a2f69a96a33db14a7c6c1bd69b43d94b6d1d5e9ef"
    end
    on_intel do
      url "https://github.com/kfet/burnbox/releases/download/v0.1.7/burnbox-0.1.7-darwin-amd64.tar.gz"
      sha256 "beaf72b4170d2a2bbf38ea02c9482d1f1e3c9be3fab0e484bae410334f68770d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/burnbox/releases/download/v0.1.7/burnbox-0.1.7-linux-arm64.tar.gz"
      sha256 "0b0d3e7d930f140551eae049c6680656b98e9b220c701659f01281634efe1c5f"
    end
    on_intel do
      url "https://github.com/kfet/burnbox/releases/download/v0.1.7/burnbox-0.1.7-linux-amd64.tar.gz"
      sha256 "2551ca9c6591c9658278bec34869de3abe3b3d6189f297e586dd2e9077131700"
    end
  end

  def install
    bin.install "burnbox"
  end

  test do
    assert_match "burnbox", shell_output("#{bin}/burnbox version 2>&1")
  end
end
