# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/gorun.rb.tmpl in
# github.com/kfet/gorun.
class Gorun < Formula
  desc "Run Go without installing Go — on-demand, verified toolchain launcher"
  homepage "https://github.com/kfet/gorun"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/gorun/releases/download/v0.1.0/gorun-0.1.0-darwin-arm64.tar.gz"
      sha256 "c9a3961911f1c0a2dd6b21d6961d4a8ae1e6bad2d4067aafa8b59e4c8446c3d4"
    end
    on_intel do
      url "https://github.com/kfet/gorun/releases/download/v0.1.0/gorun-0.1.0-darwin-amd64.tar.gz"
      sha256 "0c581561926e48aa849c877ec3852e7ef60d61a56ad8621c1b97655236b269c6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/gorun/releases/download/v0.1.0/gorun-0.1.0-linux-arm64.tar.gz"
      sha256 "eaa26ff40a10ec36d6a001f3e846d40ae1d09a9107ca71cdd182cae05b0c59a7"
    end
    on_intel do
      url "https://github.com/kfet/gorun/releases/download/v0.1.0/gorun-0.1.0-linux-amd64.tar.gz"
      sha256 "a0acbbbf4996c6d2d6dab0e45aef0536ffbf3c224e9cc443a232d8eea375d9ca"
    end
  end

  def install
    bin.install "gorun"
  end

  test do
    assert_match "gorun", shell_output("#{bin}/gorun version 2>&1")
  end
end
