# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/gorun.rb.tmpl in
# github.com/kfet/gorun.
class Gorun < Formula
  desc "Run Go without installing Go — on-demand, verified toolchain launcher"
  homepage "https://github.com/kfet/gorun"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/gorun/releases/download/v0.1.0/gorun-0.1.0-darwin-arm64.tar.gz"
      sha256 "cbcb35a00139a21b6efa017e829504177bc7980fbb6023e90faf7b6773dbd699"
    end
    on_intel do
      url "https://github.com/kfet/gorun/releases/download/v0.1.0/gorun-0.1.0-darwin-amd64.tar.gz"
      sha256 "937103099dcb37eb14452498204b1058d6c415489be475ced9b573c4ba769bc3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/gorun/releases/download/v0.1.0/gorun-0.1.0-linux-arm64.tar.gz"
      sha256 "94207ede7f30ca6b7921400c5de0eee74ab355b0ea9e1a1d77f8ea0d03d8de15"
    end
    on_intel do
      url "https://github.com/kfet/gorun/releases/download/v0.1.0/gorun-0.1.0-linux-amd64.tar.gz"
      sha256 "d07c4ff3b619fc85e6a1acab5a23561d37f8f62248ad1cbf731eae3bb04ae1d5"
    end
  end

  def install
    bin.install "gorun"
  end

  test do
    assert_match "gorun", shell_output("#{bin}/gorun version 2>&1")
  end
end

# verify-marker 1783068594
