# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/harb.rb.tmpl in
# github.com/kfet/harb.
class Harb < Formula
  desc "Self-hosted RSS server speaking the Google Reader API dialect"
  homepage "https://github.com/kfet/harb"
  version "0.6.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/harb/releases/download/v0.6.0/harb-0.6.0-darwin-arm64.tar.gz"
      sha256 "ee3bc6a85e7d95d5ed6c6251b3be86bf67f6afbd452c6a7e32cd25459d1a6100"
    end
    on_intel do
      url "https://github.com/kfet/harb/releases/download/v0.6.0/harb-0.6.0-darwin-amd64.tar.gz"
      sha256 "bfb68e2c5de7fa792b256f2d474160685922aad553a8233f7a3e90cd1cbe29af"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/harb/releases/download/v0.6.0/harb-0.6.0-linux-arm64.tar.gz"
      sha256 "636eeb05c6ad774831135593c8542486de0bb585d4c234fc9f629a864dc41cf4"
    end
    on_intel do
      url "https://github.com/kfet/harb/releases/download/v0.6.0/harb-0.6.0-linux-amd64.tar.gz"
      sha256 "a5cbc9001d3517c7d460e9dbc507c2c9e85da3cca0bec82bd3c6adbdfdf8b2f3"
    end
  end

  def install
    bin.install "harb"
  end

  test do
    assert_match "harb", shell_output("#{bin}/harb version 2>&1")
  end
end
