# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/harborrs.rb.tmpl in
# github.com/kfet/harborrs.
class Harborrs < Formula
  desc "Self-hosted RSS server speaking the Google Reader API dialect"
  homepage "https://github.com/kfet/harborrs"
  version "0.4.22"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/harborrs/releases/download/v0.4.22/harborrs-0.4.22-darwin-arm64.tar.gz"
      sha256 "718a44a6a8e253a19bd452bb91b6d57db5f32807ec69290cd4ee28a64e7f605d"
    end
    on_intel do
      url "https://github.com/kfet/harborrs/releases/download/v0.4.22/harborrs-0.4.22-darwin-amd64.tar.gz"
      sha256 "239eedec98418acb4770a1bf3b13b631fe8228a7a22bd7af7cd5cb48ce447870"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/harborrs/releases/download/v0.4.22/harborrs-0.4.22-linux-arm64.tar.gz"
      sha256 "234d8bfd3a60aadc49b9fbacd3fedd165ae94a243764945111984b65f13cfed2"
    end
    on_intel do
      url "https://github.com/kfet/harborrs/releases/download/v0.4.22/harborrs-0.4.22-linux-amd64.tar.gz"
      sha256 "36dcbdc9683832ff44a60dc230466055cb1d26d739428ed59180354b2c25e437"
    end
  end

  def install
    bin.install "harborrs"
  end

  test do
    assert_match "harborrs", shell_output("#{bin}/harborrs version 2>&1")
  end
end
