# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/harb.rb.tmpl in
# github.com/kfet/harb.
class Harb < Formula
  desc "Self-hosted RSS server speaking the Google Reader API dialect"
  homepage "https://github.com/kfet/harb"
  version "0.5.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/harb/releases/download/v0.5.1/harb-0.5.1-darwin-arm64.tar.gz"
      sha256 "0989ff8eac10adbaf9ab0d94b1148690248b35f1cec1445b7685d9b90c6e099c"
    end
    on_intel do
      url "https://github.com/kfet/harb/releases/download/v0.5.1/harb-0.5.1-darwin-amd64.tar.gz"
      sha256 "5eb2a6f5b83aa26c44049eada603a81838922065e700a2bd761f7079c294493c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/harb/releases/download/v0.5.1/harb-0.5.1-linux-arm64.tar.gz"
      sha256 "f89eecf9406abfb8bfe4cd8857e6aff9e227908823b189b06a3bf97e85e7afd1"
    end
    on_intel do
      url "https://github.com/kfet/harb/releases/download/v0.5.1/harb-0.5.1-linux-amd64.tar.gz"
      sha256 "35fd9fb046ea785ec9c22ac2b2857c46371ebb5976cb9012a670ce8b860ccd48"
    end
  end

  def install
    bin.install "harb"
  end

  test do
    assert_match "harb", shell_output("#{bin}/harb version 2>&1")
  end
end
