# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/harborrs.rb.tmpl in
# github.com/kfet/harborrs.
class Harborrs < Formula
  desc "Self-hosted RSS server speaking the Google Reader API dialect"
  homepage "https://github.com/kfet/harborrs"
  version "0.4.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/harborrs/releases/download/v0.4.6/harborrs-0.4.6-darwin-arm64.tar.gz"
      sha256 "64dc52f7f88ec15173c5853e7ec9934d967629f05a1a8d0b40831ba4c046880a"
    end
    on_intel do
      url "https://github.com/kfet/harborrs/releases/download/v0.4.6/harborrs-0.4.6-darwin-amd64.tar.gz"
      sha256 "17b929552bfef5e0237f8b72afe22e579489c05a9dc137420e4a4eee998d3ca9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/harborrs/releases/download/v0.4.6/harborrs-0.4.6-linux-arm64.tar.gz"
      sha256 "650ed2551b8c488f414f49bafb7e72ac03755bcd0f335d78b55f1dc9399a8b45"
    end
    on_intel do
      url "https://github.com/kfet/harborrs/releases/download/v0.4.6/harborrs-0.4.6-linux-amd64.tar.gz"
      sha256 "e67f72c21f29941dd8f25da37333017e598c5b951b598ba929f89133e25a753c"
    end
  end

  def install
    bin.install "harborrs"
  end

  test do
    assert_match "harborrs", shell_output("#{bin}/harborrs version 2>&1")
  end
end
