# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/harb.rb.tmpl in
# github.com/kfet/harb.
class Harb < Formula
  desc "Self-hosted RSS server speaking the Google Reader API dialect"
  homepage "https://github.com/kfet/harb"
  version "0.19.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/harb/releases/download/v0.19.1/harb-0.19.1-darwin-arm64.tar.gz"
      sha256 "6be1965a27e46e4444c328948c7ae5757671c22d38fdba16ca2e2e4860ad277e"
    end
    on_intel do
      url "https://github.com/kfet/harb/releases/download/v0.19.1/harb-0.19.1-darwin-amd64.tar.gz"
      sha256 "daf20d090e2f1407f99b5fc79e14a4413474098513c1ead6cbe5436d530bde26"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/harb/releases/download/v0.19.1/harb-0.19.1-linux-arm64.tar.gz"
      sha256 "d1b87760d9344141815722b8d89d12c2bbd37317d8c537693881f3be8b90be5d"
    end
    on_intel do
      url "https://github.com/kfet/harb/releases/download/v0.19.1/harb-0.19.1-linux-amd64.tar.gz"
      sha256 "fc38bd5278495dcd977c153a6b3dc529725e7ea797d9caaf6c3c7780f1731ef5"
    end
  end

  def install
    bin.install "harb"
  end

  test do
    assert_match "harb", shell_output("#{bin}/harb version 2>&1")
  end
end
