# typed: false
# frozen_string_literal: true

# This file is auto-generated by the release pipeline.
# Do not edit by hand — see packaging/homebrew/harb.rb.tmpl in
# github.com/kfet/harb.
class Harb < Formula
  desc "Self-hosted RSS server speaking the Google Reader API dialect"
  homepage "https://github.com/kfet/harb"
  version "0.12.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kfet/harb/releases/download/v0.12.2/harb-0.12.2-darwin-arm64.tar.gz"
      sha256 "e12f4c7965dc6466eadd03ac81a24ac16ed7b60120709f78a2093d96b062bb36"
    end
    on_intel do
      url "https://github.com/kfet/harb/releases/download/v0.12.2/harb-0.12.2-darwin-amd64.tar.gz"
      sha256 "a0c46a77fe06bbe6b8f5996e8d7f83d49e56fda71fd8816a418815c7f004071e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kfet/harb/releases/download/v0.12.2/harb-0.12.2-linux-arm64.tar.gz"
      sha256 "fbb80ced31e85c8831ca5a2ad6e15af73cf58c4b8c41b0f90f7fb525c30af2bb"
    end
    on_intel do
      url "https://github.com/kfet/harb/releases/download/v0.12.2/harb-0.12.2-linux-amd64.tar.gz"
      sha256 "91c133ab183a08080e22dd12cabb634d17c98000afa1bfd03d2a9178bce29d06"
    end
  end

  def install
    bin.install "harb"
  end

  test do
    assert_match "harb", shell_output("#{bin}/harb version 2>&1")
  end
end
